version: '3.8.5'

services:
  app:
    build:
      context: .
    environment:
      - SECRET_KEY=thecoolkidskey
      - ALLOWED_HOSTS=127.0.0.1,localhost,40.71.119.30

  proxy:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data: