version: '3.7'

services:
  web:
    build: ./app
    command: gunicorn vancouvar.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./app/nginx
    ports:
      - 1337:80
    depends_on:
      - web      