# Generated by Django 3.1.7 on 2021-05-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstats',
            name='all_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailstats',
            name='daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailstats',
            name='monthly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailstats',
            name='weekly',
            field=models.IntegerField(default=0),
        ),
    ]
