# Generated by Django 3.2 on 2021-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adoption_strategy',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_industry',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_website',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='competitive_advantage',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='conversion_rate',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='core_proceed',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_arpu',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_cac',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_customers',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_round',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_stage',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_valuation',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='customer_ltv',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_address',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='estimated_tam',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='exit_strategy',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='founder_background',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='founder_count',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gross_margin',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='incorporated_country',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='incorporated_state',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='investor_return',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='magic_number',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_revenue',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='northstar_metric',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='problem_discovered',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='product_availability',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='raised_round',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='retention_rate',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='solution_proposed',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='target_market',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='technology_stack',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
