# Generated by Django 3.1.7 on 2021-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210429_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
