# Generated by Django 3.1.7 on 2021-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210503_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_emails_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_balance',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_emails_sent',
            field=models.IntegerField(default=0),
        ),
    ]
