# Generated by Django 3.1.7 on 2021-05-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210504_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='all_time_emails_sent',
            field=models.IntegerField(default=0),
        ),
    ]
