# Generated by Django 3.1.7 on 2021-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_plan',
            field=models.CharField(default='CURIOUS', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_email_allowance',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_emails_sent',
            field=models.IntegerField(default=0),
        ),
    ]
